Repository RogueEdit/pyRogue, pull requests merged in 2024-05, with the labels that each got.

#2 Fixing codeql.yaml
  .github/workflows/codeql.yml
Labels: workflow

#4 Update README.md
  README.md
Labels: documentation

#15 Update README.md
  README.md
Labels: documentation

#20 New features
  .github/preview.png
  README.md
  src/data/passive.json
  src/main.py
  src/modules/eggLogic.py
  src/modules/rogueApiClass.py
  src/modules/rogueClass.py
  src/modules/seleniumLogic.py
Labels: enhancement, feature, database

#39 Triage: Immediate response
  .github/preview.png
  .github/previews/achievements.png
  .github/previews/egg-list.png
  .github/previews/eggs.gif
  .github/previews/field1.png
  .github/previews/field2.png
  .github/previews/main.png
  .github/previews/starter.png
  .github/previews/stats.png
  .github/previews/voucher.png
  PREVIEW.md
  README.md
  src/main.py
  src/modules/rogueClass.py
Labels: triage
